CONTIKI_PROJECT = adcTest
all: $(CONTIKI_PROJECT)

ifeq ($(CONTIKI),)
$(error You must set the environment variable CONTIKI so it points to the root of contiki-inga.)
endif

include $(CONTIKI)/Makefile.include
